### ISSUE TITLE
1.8 Tasks

### ISSUE THREAD

**Issue by RobertBColton** [IsmAvatar/LateralGM#46]
This is a list of things I am working on and we need to do before reaching stable build 2.0

- [x] Add Preferences Panel
- [x] Add language options to preferences panel
- [x] Add multiple settings
- [x] Merge JoshEdit
- [x] GTK fonts need some work, also in #27
- [x] Object information window could be used for timelines as well to get a pastebin style dump of all the moments, implemented as of #58 
- [x] When copying/pasting to JoshEdit code editor, if you go over the number of lines scrollbar doesnt show up you have to close and reopen the code editor
- [x] Added multiple file selection for sprite previewer when adding subimages in #58
- [x] Printing dialog shows but does not print yet this requires writing a document listener and painter for the editors that are capable of printing, such Game Information, Resource Information (timelines/objects), script and code editors
- [x] Save/load options for code editor 
- [x] Context menu for action editor, this has been partially done by me but I don't feel like recoding the transfer handler the delete option works in the context, but not enough buttons for me to enable it
- [x] Figure out what to do about the manual button NOTICE: I have temporarily added the preference option to set a path to your documentation it tells the default system program to open the file, if the path contains http:// it will open it in the web browser, default is the ENIGMA Wiki
- [x] Add run/debug/compile buttons to the main toolbar
- [x] Fix the compile button
- [x] Find and replace button to code editor window
- [x] Add subimage from file button for sprite previewer 
- [x] Make resources show up in code completion window
- [x] Fix find and replace window bugs, such as replace all not doing anything, WARNING! replace all works now but the find window does not start with the caret position in the correct location
e when you are working in the engine you may add new functions etc, so idk
- [x] Finish preferences panel
- [x] GMX Support, (*.xml) studio project file
- [ ] GMZ Support, 7zip'd GMX file
- [x] preferences can be overridden by simply placing preferences-en_US.properties directly next to the jar file be aware that -en_US locale be different, implemented in #58 
- [ ] Come up with a method for swapping action libraries in and out like extensions, so you can choose the specific ones you want
- [ ] Tree/Event panel docking, with a little extra code hacking them onto toolbars, I already did part of this which is commented out because it don't work exactly right with a split pane separating it from the MDI area, or at least add a preference for where it is on load, I've grown used to it on the left though because its more natural to a right handed person with a standard keyboard setup
- [x] Resource tree collapse/uncollapse buttons under GTK theme are cutoff by a few pixels, see picture...
http://oi43.tinypic.com/2v0dhy1.jpg
I've experienced this same issue with wxWidgets
https://bugs.openjdk.java.net/browse/JDK-8152968

**Comment by RobertBColton** [comment]
These other two tasks never came about but the rest are ok for now. I am closing this because we are several versions ahead of this now.
